// Mocks generated by Mockito 5.4.6 from annotations
// in omi/test/unit/utils/audio/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter_sound/flutter_sound.dart' as _i3;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlutterSoundPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSoundPlayer extends _i1.Mock
    implements _i3.FlutterSoundPlayer {
  MockFlutterSoundPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i3.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _i3.PlayerState.isStopped,
      ) as _i3.PlayerState);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  bool get isStopped => (super.noSuchMethod(
        Invocation.getter(#isStopped),
        returnValue: false,
      ) as bool);

  @override
  void setLogLevel(_i2.Level? aLevel) => super.noSuchMethod(
        Invocation.method(
          #setLogLevel,
          [aLevel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateProgress({
    int? duration = 0,
    int? position = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateProgress,
          [],
          {
            #duration: duration,
            #position: position,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePlaybackState(int? state) => super.noSuchMethod(
        Invocation.method(
          #updatePlaybackState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void needSomeFood(int? ln) => super.noSuchMethod(
        Invocation.method(
          #needSomeFood,
          [ln],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void audioPlayerFinished(int? state) => super.noSuchMethod(
        Invocation.method(
          #audioPlayerFinished,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openPlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #openPlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pausePlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pausePlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumePlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resumePlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startPlayerCompleted(
    int? state,
    bool? success,
    int? duration,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startPlayerCompleted,
          [
            state,
            success,
            duration,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopPlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #stopPlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i2.Level? logLevel,
    String? msg,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            logLevel,
            msg,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isOpen() => (super.noSuchMethod(
        Invocation.method(
          #isOpen,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i3.FlutterSoundPlayer?> openPlayer(
          {dynamic isBGService = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openPlayer,
          [],
          {#isBGService: isBGService},
        ),
        returnValue: _i4.Future<_i3.FlutterSoundPlayer?>.value(),
      ) as _i4.Future<_i3.FlutterSoundPlayer?>);

  @override
  _i4.Future<void> closePlayer() => (super.noSuchMethod(
        Invocation.method(
          #closePlayer,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.PlayerState> getPlayerState() => (super.noSuchMethod(
        Invocation.method(
          #getPlayerState,
          [],
        ),
        returnValue:
            _i4.Future<_i3.PlayerState>.value(_i3.PlayerState.isStopped),
      ) as _i4.Future<_i3.PlayerState>);

  @override
  _i4.Future<Map<String, Duration>> getProgress() => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, Duration>>.value(<String, Duration>{}),
      ) as _i4.Future<Map<String, Duration>>);

  @override
  _i4.Future<bool> isDecoderSupported(_i3.Codec? codec) => (super.noSuchMethod(
        Invocation.method(
          #isDecoderSupported,
          [codec],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setSubscriptionDuration(Duration? duration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionDuration,
          [duration],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Duration?> startPlayer({
    _i3.Codec? codec = _i3.Codec.aacADTS,
    int? sampleRate = 16000,
    int? numChannels = 1,
    String? fromURI,
    _i5.Uint8List? fromDataBuffer,
    _i3.TWhenFinished? whenFinished,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayer,
          [],
          {
            #codec: codec,
            #sampleRate: sampleRate,
            #numChannels: numChannels,
            #fromURI: fromURI,
            #fromDataBuffer: fromDataBuffer,
            #whenFinished: whenFinished,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> startPlayerFromMic({
    int? sampleRate = 44000,
    int? numChannels = 1,
    int? bufferSize = 8192,
    dynamic enableVoiceProcessing = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayerFromMic,
          [],
          {
            #sampleRate: sampleRate,
            #numChannels: numChannels,
            #bufferSize: bufferSize,
            #enableVoiceProcessing: enableVoiceProcessing,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startPlayerFromStream({
    _i3.Codec? codec = _i3.Codec.pcm16,
    bool? interleaved = true,
    int? numChannels = 1,
    int? sampleRate = 16000,
    int? bufferSize = 8192,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayerFromStream,
          [],
          {
            #codec: codec,
            #interleaved: interleaved,
            #numChannels: numChannels,
            #sampleRate: sampleRate,
            #bufferSize: bufferSize,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> feedFromStream(_i5.Uint8List? buffer) => (super.noSuchMethod(
        Invocation.method(
          #feedFromStream,
          [buffer],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> feedF32FromStream(List<_i5.Float32List>? buffer) =>
      (super.noSuchMethod(
        Invocation.method(
          #feedF32FromStream,
          [buffer],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> feedInt16FromStream(List<_i5.Int16List>? buffer) =>
      (super.noSuchMethod(
        Invocation.method(
          #feedInt16FromStream,
          [buffer],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> feedUint8FromStream(_i5.Uint8List? buffer) =>
      (super.noSuchMethod(
        Invocation.method(
          #feedUint8FromStream,
          [buffer],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> stopPlayer() => (super.noSuchMethod(
        Invocation.method(
          #stopPlayer,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pausePlayer() => (super.noSuchMethod(
        Invocation.method(
          #pausePlayer,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resumePlayer() => (super.noSuchMethod(
        Invocation.method(
          #resumePlayer,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToPlayer(Duration? duration) => (super.noSuchMethod(
        Invocation.method(
          #seekToPlayer,
          [duration],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setVolumePan(
    double? volume,
    double? pan,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVolumePan,
          [
            volume,
            pan,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getResourcePath() => (super.noSuchMethod(
        Invocation.method(
          #getResourcePath,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}
