// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.omi.offline

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonCommunicatorPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Discovered BLE peripheral info passed from native to Dart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BlePeripheral (
  val uuid: String,
  val name: String,
  val rssi: Long,
  val serviceUuids: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BlePeripheral {
      val uuid = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val rssi = pigeonVar_list[2] as Long
      val serviceUuids = pigeonVar_list[3] as List<String>
      return BlePeripheral(uuid, name, rssi, serviceUuids)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      name,
      rssi,
      serviceUuids,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BlePeripheral) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonCommunicatorPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Discovered BLE service with its characteristic UUIDs.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BleService (
  val uuid: String,
  val characteristicUuids: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleService {
      val uuid = pigeonVar_list[0] as String
      val characteristicUuids = pigeonVar_list[1] as List<String>
      return BleService(uuid, characteristicUuids)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      characteristicUuids,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BleService) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonCommunicatorPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonCommunicatorPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlePeripheral.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleService.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BlePeripheral -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BleService -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart → Native: commands sent from Flutter to the native BLE module.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BleHostApi {
  fun startScan(timeoutSeconds: Long, serviceUuids: List<String>)
  fun stopScan()
  fun manageDevice(uuid: String, requiresBond: Boolean)
  fun unmanageDevice(uuid: String)
  fun removeBond(uuid: String)
  fun disconnectPeripheral(uuid: String)
  /**
   * (Android only) Reschedule the WorkManager periodic background sync with
   * the given interval. Pass 0 or negative to cancel. iOS no-op.
   */
  fun rescheduleBackgroundSync(intervalMinutes: Long)
  fun requestBond(uuid: String, callback: (Result<Boolean>) -> Unit)
  fun readCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String, callback: (Result<ByteArray>) -> Unit)
  fun writeCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String, data: ByteArray, callback: (Result<Unit>) -> Unit)
  fun subscribeCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String)
  fun unsubscribeCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String)
  fun getBluetoothState(): String
  fun isPeripheralConnected(uuid: String): Boolean
  /**
   * (Android only) Addresses the OS currently holds a pairing key for,
   * uppercased to match the ids native hands out everywhere else.
   *
   * Find Devices asks so it can mark which row is the Omi this phone is paired
   * to — the stored preference cannot answer that, since it still names the
   * device after a DFU wipes the bond. The whole set rather than a per-address
   * query: it is one IPC instead of one per row, and normalizing the address is
   * then native's job rather than every caller's. A local lookup, no radio
   * traffic. iOS returns empty (CoreBluetooth exposes no bond state).
   */
  fun getBondedDeviceIds(): List<String>
  /** (Android only) Check if any CompanionDeviceManager association exists. */
  fun hasCompanionDeviceAssociation(): Boolean
  /** (Android only) Initiate CompanionDeviceManager association for a device. */
  fun requestCompanionDeviceAssociation(deviceAddress: String, callback: (Result<String>) -> Unit)
  /**
   * (Android only) Download a storage file natively, bypassing the per-packet
   * platform-channel dispatch that throttles in background. Accumulates BLE
   * notifications on the binder thread and writes directly to [outputPath].
   * iOS throws 'unimplemented' — callers must check Platform.isAndroid.
   */
  fun downloadStorageFile(peripheralUuid: String, fileIndex: Long, offset: Long, timerStart: Long, outputPath: String, callback: (Result<Unit>) -> Unit)
  /**
   * (Android only) Acquire a CPU partial wake-lock so the OS does not throttle
   * the processing isolate during VAD inference. Call before processAll; release
   * in finally. iOS no-op.
   */
  fun acquireProcessingWakeLock()
  /**
   * (Android only) Release the CPU partial wake-lock acquired by
   * [acquireProcessingWakeLock]. iOS no-op.
   */
  fun releaseProcessingWakeLock()
  /**
   * (Android only) Push the next-sync epoch-ms to OmiBleForegroundService so it
   * can display a native Chronometer countdown without Dart involvement.
   * Pass 0 to clear (e.g. Manual Only mode). iOS no-op.
   */
  fun setNextSyncTime(timestampMs: Long)
  /**
   * (Android only) Push the device battery level and the epoch-ms when it was
   * read to OmiBleForegroundService so ID 2001 shows "78% · 3:45 PM".
   * Call whenever a battery reading is obtained. iOS no-op.
   */
  fun setDeviceBattery(level: Long, timestampMs: Long)
  /**
   * (Android only) Set the single foreground-service notification's title and
   * text directly. Used by the Dart sync state machine to drive the one
   * persistent notification (idle / connecting / syncing / processing / …).
   * While a status is set, native suppresses its own connection-state text so
   * the two don't fight. iOS no-op.
   */
  fun setSyncStatus(title: String, text: String)
  /**
   * (Android only) Keep the foreground service alive with no device connected
   * so the idle "Next sync / Last Sync" notification persists across BLE
   * disconnect and app background. true while auto-sync is on and a device is
   * bound; false in Manual Only / unbound (reverts to connection-only service
   * lifetime). iOS no-op.
   */
  fun setPersistentNotification(enabled: Boolean)
  /**
   * (Android only) Clear any Dart-pushed status text and let native resume
   * owning the notification (connection state / idle). iOS no-op.
   */
  fun clearSyncStatus()

  companion object {
    /** The codec used by BleHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonCommunicatorPigeonCodec()
    }
    /** Sets up an instance of `BleHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BleHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutSecondsArg = args[0] as Long
            val serviceUuidsArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.startScan(timeoutSecondsArg, serviceUuidsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScan()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.manageDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            val requiresBondArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.manageDevice(uuidArg, requiresBondArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.unmanageDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.unmanageDevice(uuidArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.removeBond$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeBond(uuidArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.disconnectPeripheral$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disconnectPeripheral(uuidArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.rescheduleBackgroundSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val intervalMinutesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.rescheduleBackgroundSync(intervalMinutesArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.requestBond$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            api.requestBond(uuidArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonCommunicatorPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralUuidArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.readCharacteristic(peripheralUuidArg, serviceUuidArg, characteristicUuidArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonCommunicatorPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralUuidArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val dataArg = args[3] as ByteArray
            api.writeCharacteristic(peripheralUuidArg, serviceUuidArg, characteristicUuidArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.subscribeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralUuidArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.subscribeCharacteristic(peripheralUuidArg, serviceUuidArg, characteristicUuidArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.unsubscribeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralUuidArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.unsubscribeCharacteristic(peripheralUuidArg, serviceUuidArg, characteristicUuidArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.getBluetoothState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBluetoothState())
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.isPeripheralConnected$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.isPeripheralConnected(uuidArg))
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.getBondedDeviceIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBondedDeviceIds())
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.hasCompanionDeviceAssociation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasCompanionDeviceAssociation())
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.requestCompanionDeviceAssociation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceAddressArg = args[0] as String
            api.requestCompanionDeviceAssociation(deviceAddressArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonCommunicatorPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.downloadStorageFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val peripheralUuidArg = args[0] as String
            val fileIndexArg = args[1] as Long
            val offsetArg = args[2] as Long
            val timerStartArg = args[3] as Long
            val outputPathArg = args[4] as String
            api.downloadStorageFile(peripheralUuidArg, fileIndexArg, offsetArg, timerStartArg, outputPathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonCommunicatorPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.acquireProcessingWakeLock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.acquireProcessingWakeLock()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.releaseProcessingWakeLock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.releaseProcessingWakeLock()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.setNextSyncTime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timestampMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setNextSyncTime(timestampMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.setDeviceBattery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as Long
            val timestampMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setDeviceBattery(levelArg, timestampMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.setSyncStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val textArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.setSyncStatus(titleArg, textArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.setPersistentNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setPersistentNotification(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_pigeon.BleHostApi.clearSyncStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearSyncStatus()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonCommunicatorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BleFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BleFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonCommunicatorPigeonCodec()
    }
  }
  fun onBluetoothStateChanged(stateArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onBluetoothStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPeripheralDiscovered(peripheralArg: BlePeripheral, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onPeripheralDiscovered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDeviceReady(peripheralUuidArg: String, servicesArg: List<BleService>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onDeviceReady$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralUuidArg, servicesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPeripheralDisconnected(peripheralUuidArg: String, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onPeripheralDisconnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralUuidArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCharacteristicValueUpdated(peripheralUuidArg: String, serviceUuidArg: String, characteristicUuidArg: String, valueArg: ByteArray, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onCharacteristicValueUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralUuidArg, serviceUuidArg, characteristicUuidArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStateRestored(peripheralUuidsArg: List<String>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onStateRestored$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralUuidsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Called by native (iOS BGProcessingTask / Android WorkManager) when a
   * background sync should be triggered. Equivalent to a timer-fired sync tick
   * but sourced from the OS scheduler instead of the Dart timer.
   */
  fun onBackgroundSyncRequested(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onBackgroundSyncRequested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Diagnostic records native produced, as complete JSON lines in
   * `DebugLogManager`'s schema, for Dart to append to the debug log.
   *
   * Native used to append to that file itself. It cannot: Dart's
   * `FileMode.append` is **not** `O_APPEND` — it resolves the write offset when
   * the file is opened, not when the bytes are written — while Kotlin's
   * `FileOutputStream(append = true)` is. So a native record landing between
   * Dart's open and Dart's write was overwritten by it, one-directionally, and
   * native emits precisely during the Dart logging bursts that describe the same
   * disconnect. A 4.4 h capture on 2026-08-31 kept **one** native record out of
   * eight expected, and the survivor was a deliberate disconnect rather than one
   * of the timeouts the records exist to classify.
   *
   * Lines arrive pre-encoded so the timestamp inside each one is still the
   * instant native observed the event, not the instant Dart got the batch.
   */
  fun onNativeLogRecords(linesArg: List<String>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onNativeLogRecords$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(linesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonCommunicatorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
