// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonCommunicator(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonCommunicator(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonCommunicator(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonCommunicator(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonCommunicator(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonCommunicator(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Discovered BLE peripheral info passed from native to Dart.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BlePeripheral: Hashable {
  var uuid: String
  var name: String
  var rssi: Int64
  var serviceUuids: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BlePeripheral? {
    let uuid = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let rssi = pigeonVar_list[2] as! Int64
    let serviceUuids = pigeonVar_list[3] as! [String]

    return BlePeripheral(
      uuid: uuid,
      name: name,
      rssi: rssi,
      serviceUuids: serviceUuids
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      name,
      rssi,
      serviceUuids,
    ]
  }
  static func == (lhs: BlePeripheral, rhs: BlePeripheral) -> Bool {
    return deepEqualsPigeonCommunicator(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonCommunicator(value: toList(), hasher: &hasher)
  }
}

/// Discovered BLE service with its characteristic UUIDs.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BleService: Hashable {
  var uuid: String
  var characteristicUuids: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleService? {
    let uuid = pigeonVar_list[0] as! String
    let characteristicUuids = pigeonVar_list[1] as! [String]

    return BleService(
      uuid: uuid,
      characteristicUuids: characteristicUuids
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      characteristicUuids,
    ]
  }
  static func == (lhs: BleService, rhs: BleService) -> Bool {
    return deepEqualsPigeonCommunicator(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonCommunicator(value: toList(), hasher: &hasher)
  }
}

private class PigeonCommunicatorPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BlePeripheral.fromList(self.readValue() as! [Any?])
    case 130:
      return BleService.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonCommunicatorPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BlePeripheral {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BleService {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonCommunicatorPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonCommunicatorPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonCommunicatorPigeonCodecWriter(data: data)
  }
}

class PigeonCommunicatorPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonCommunicatorPigeonCodec(readerWriter: PigeonCommunicatorPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WatchRecorderHostAPI {
  func startRecording() throws
  func stopRecording() throws
  func sendAudioData(audioData: FlutterStandardTypedData) throws
  func sendAudioChunk(audioChunk: FlutterStandardTypedData, chunkIndex: Int64, isLast: Bool, sampleRate: Double) throws
  func isWatchPaired() throws -> Bool
  func isWatchReachable() throws -> Bool
  func isWatchSessionSupported() throws -> Bool
  func isWatchAppInstalled() throws -> Bool
  func requestWatchMicrophonePermission() throws
  func requestMainAppMicrophonePermission() throws
  func checkMainAppMicrophonePermission() throws -> Bool
  func getWatchBatteryLevel() throws -> Double
  func getWatchBatteryState() throws -> Int64
  func requestWatchBatteryUpdate() throws
  func getWatchInfo() throws -> [String: String]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WatchRecorderHostAPISetup {
  static var codec: FlutterStandardMessageCodec { PigeonCommunicatorPigeonCodec.shared }
  /// Sets up an instance of `WatchRecorderHostAPI` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WatchRecorderHostAPI?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.startRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecordingChannel.setMessageHandler { _, reply in
        do {
          try api.startRecording()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startRecordingChannel.setMessageHandler(nil)
    }
    let stopRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.stopRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingChannel.setMessageHandler { _, reply in
        do {
          try api.stopRecording()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopRecordingChannel.setMessageHandler(nil)
    }
    let sendAudioDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.sendAudioData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendAudioDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioDataArg = args[0] as! FlutterStandardTypedData
        do {
          try api.sendAudioData(audioData: audioDataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendAudioDataChannel.setMessageHandler(nil)
    }
    let sendAudioChunkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.sendAudioChunk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendAudioChunkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioChunkArg = args[0] as! FlutterStandardTypedData
        let chunkIndexArg = args[1] as! Int64
        let isLastArg = args[2] as! Bool
        let sampleRateArg = args[3] as! Double
        do {
          try api.sendAudioChunk(audioChunk: audioChunkArg, chunkIndex: chunkIndexArg, isLast: isLastArg, sampleRate: sampleRateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendAudioChunkChannel.setMessageHandler(nil)
    }
    let isWatchPairedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.isWatchPaired\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWatchPairedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWatchPaired()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWatchPairedChannel.setMessageHandler(nil)
    }
    let isWatchReachableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.isWatchReachable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWatchReachableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWatchReachable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWatchReachableChannel.setMessageHandler(nil)
    }
    let isWatchSessionSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.isWatchSessionSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWatchSessionSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWatchSessionSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWatchSessionSupportedChannel.setMessageHandler(nil)
    }
    let isWatchAppInstalledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.isWatchAppInstalled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWatchAppInstalledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWatchAppInstalled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWatchAppInstalledChannel.setMessageHandler(nil)
    }
    let requestWatchMicrophonePermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.requestWatchMicrophonePermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestWatchMicrophonePermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestWatchMicrophonePermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestWatchMicrophonePermissionChannel.setMessageHandler(nil)
    }
    let requestMainAppMicrophonePermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.requestMainAppMicrophonePermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMainAppMicrophonePermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestMainAppMicrophonePermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestMainAppMicrophonePermissionChannel.setMessageHandler(nil)
    }
    let checkMainAppMicrophonePermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.checkMainAppMicrophonePermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkMainAppMicrophonePermissionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.checkMainAppMicrophonePermission()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkMainAppMicrophonePermissionChannel.setMessageHandler(nil)
    }
    let getWatchBatteryLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.getWatchBatteryLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWatchBatteryLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getWatchBatteryLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getWatchBatteryLevelChannel.setMessageHandler(nil)
    }
    let getWatchBatteryStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.getWatchBatteryState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWatchBatteryStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getWatchBatteryState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getWatchBatteryStateChannel.setMessageHandler(nil)
    }
    let requestWatchBatteryUpdateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.requestWatchBatteryUpdate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestWatchBatteryUpdateChannel.setMessageHandler { _, reply in
        do {
          try api.requestWatchBatteryUpdate()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestWatchBatteryUpdateChannel.setMessageHandler(nil)
    }
    let getWatchInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.WatchRecorderHostAPI.getWatchInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWatchInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getWatchInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getWatchInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WatchRecorderFlutterAPIProtocol {
  func onRecordingStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRecordingStopped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioData(audioData audioDataArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAudioChunk(audioChunk audioChunkArg: FlutterStandardTypedData, chunkIndex chunkIndexArg: Int64, isLast isLastArg: Bool, sampleRate sampleRateArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRecordingError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMicrophonePermissionResult(granted grantedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMainAppMicrophonePermissionResult(granted grantedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWatchBatteryUpdate(batteryLevel batteryLevelArg: Double, batteryState batteryStateArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WatchRecorderFlutterAPI: WatchRecorderFlutterAPIProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonCommunicatorPigeonCodec {
    return PigeonCommunicatorPigeonCodec.shared
  }
  func onRecordingStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onRecordingStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRecordingStopped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onRecordingStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioData(audioData audioDataArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onAudioData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([audioDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAudioChunk(audioChunk audioChunkArg: FlutterStandardTypedData, chunkIndex chunkIndexArg: Int64, isLast isLastArg: Bool, sampleRate sampleRateArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onAudioChunk\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([audioChunkArg, chunkIndexArg, isLastArg, sampleRateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRecordingError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onRecordingError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMicrophonePermissionResult(granted grantedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onMicrophonePermissionResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([grantedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMainAppMicrophonePermissionResult(granted grantedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onMainAppMicrophonePermissionResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([grantedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onWatchBatteryUpdate(batteryLevel batteryLevelArg: Double, batteryState batteryStateArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.WatchRecorderFlutterAPI.onWatchBatteryUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([batteryLevelArg, batteryStateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Dart → Native: commands sent from Flutter to the native BLE module.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BleHostApi {
  func startScan(timeout timeoutSeconds: Int64, serviceUuids: [String]) throws
  func stopScan() throws
  func manageDevice(uuid: String, requiresBond: Bool) throws
  func unmanageDevice(uuid: String) throws
  func disconnectPeripheral(uuid: String) throws
  /// (Android only) Reschedule the WorkManager periodic background sync with
  /// the given interval. Pass 0 or negative to cancel. iOS no-op.
  func rescheduleBackgroundSync(intervalMinutes: Int64) throws
  func requestBond(uuid: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func readCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func writeCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String, data: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func subscribeCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String) throws
  func unsubscribeCharacteristic(peripheralUuid: String, serviceUuid: String, characteristicUuid: String) throws
  func getBluetoothState() throws -> String
  func isPeripheralConnected(uuid: String) throws -> Bool
  /// (Android only) Check if any CompanionDeviceManager association exists.
  func hasCompanionDeviceAssociation() throws -> Bool
  /// (Android only) Initiate CompanionDeviceManager association for a device.
  func requestCompanionDeviceAssociation(deviceAddress: String, completion: @escaping (Result<String, Error>) -> Void)
  /// (Android only) Download a storage file natively, bypassing the per-packet
  /// platform-channel dispatch that throttles in background. Accumulates BLE
  /// notifications on the binder thread and writes directly to [outputPath].
  /// iOS throws 'unimplemented' — callers must check Platform.isAndroid.
  func downloadStorageFile(peripheralUuid: String, fileIndex: Int64, offset: Int64, timerStart: Int64, outputPath: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// (Android only) Acquire a CPU partial wake-lock so the OS does not throttle
  /// the processing isolate during VAD inference. Call before processAll; release
  /// in finally. iOS no-op.
  func acquireProcessingWakeLock() throws
  /// (Android only) Release the CPU partial wake-lock acquired by
  /// [acquireProcessingWakeLock]. iOS no-op.
  func releaseProcessingWakeLock() throws
  /// (Android only) Push the next-sync epoch-ms to OmiBleForegroundService so it
  /// can display a native Chronometer countdown without Dart involvement.
  /// Pass 0 to clear (e.g. Manual Only mode). iOS no-op.
  func setNextSyncTime(timestampMs: Int64) throws
  /// (Android only) Push the device battery level and the epoch-ms when it was
  /// read to OmiBleForegroundService so ID 2001 shows "78% · 3:45 PM".
  /// Call whenever a battery reading is obtained. iOS no-op.
  func setDeviceBattery(level: Int64, timestampMs: Int64) throws
  /// (Android only) Set the single foreground-service notification's title and
  /// text directly. Used by the Dart sync state machine to drive the one
  /// persistent notification (idle / connecting / syncing / processing / …).
  /// While a status is set, native suppresses its own connection-state text so
  /// the two don't fight. iOS no-op.
  func setSyncStatus(title: String, text: String) throws
  /// (Android only) Keep the foreground service alive with no device connected
  /// so the idle "Next sync / Last Sync" notification persists across BLE
  /// disconnect and app background. true while auto-sync is on and a device is
  /// bound; false in Manual Only / unbound (reverts to connection-only service
  /// lifetime). iOS no-op.
  func setPersistentNotification(enabled: Bool) throws
  /// (Android only) Clear any Dart-pushed status text and let native resume
  /// owning the notification (connection state / idle). iOS no-op.
  func clearSyncStatus() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BleHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonCommunicatorPigeonCodec.shared }
  /// Sets up an instance of `BleHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BleHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutSecondsArg = args[0] as! Int64
        let serviceUuidsArg = args[1] as! [String]
        do {
          try api.startScan(timeout: timeoutSecondsArg, serviceUuids: serviceUuidsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        do {
          try api.stopScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let manageDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.manageDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      manageDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        let requiresBondArg = args[1] as! Bool
        do {
          try api.manageDevice(uuid: uuidArg, requiresBond: requiresBondArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      manageDeviceChannel.setMessageHandler(nil)
    }
    let unmanageDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.unmanageDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unmanageDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        do {
          try api.unmanageDevice(uuid: uuidArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unmanageDeviceChannel.setMessageHandler(nil)
    }
    let disconnectPeripheralChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.disconnectPeripheral\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectPeripheralChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        do {
          try api.disconnectPeripheral(uuid: uuidArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectPeripheralChannel.setMessageHandler(nil)
    }
    /// (Android only) Reschedule the WorkManager periodic background sync with
    /// the given interval. Pass 0 or negative to cancel. iOS no-op.
    let rescheduleBackgroundSyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.rescheduleBackgroundSync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rescheduleBackgroundSyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let intervalMinutesArg = args[0] as! Int64
        do {
          try api.rescheduleBackgroundSync(intervalMinutes: intervalMinutesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rescheduleBackgroundSyncChannel.setMessageHandler(nil)
    }
    let requestBondChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.requestBond\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestBondChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        api.requestBond(uuid: uuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestBondChannel.setMessageHandler(nil)
    }
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.readCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralUuidArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.readCharacteristic(peripheralUuid: peripheralUuidArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.writeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralUuidArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let dataArg = args[3] as! FlutterStandardTypedData
        api.writeCharacteristic(peripheralUuid: peripheralUuidArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, data: dataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    let subscribeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.subscribeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      subscribeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralUuidArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        do {
          try api.subscribeCharacteristic(peripheralUuid: peripheralUuidArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      subscribeCharacteristicChannel.setMessageHandler(nil)
    }
    let unsubscribeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.unsubscribeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unsubscribeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralUuidArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        do {
          try api.unsubscribeCharacteristic(peripheralUuid: peripheralUuidArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unsubscribeCharacteristicChannel.setMessageHandler(nil)
    }
    let getBluetoothStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.getBluetoothState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBluetoothStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBluetoothState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBluetoothStateChannel.setMessageHandler(nil)
    }
    let isPeripheralConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.isPeripheralConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPeripheralConnectedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        do {
          let result = try api.isPeripheralConnected(uuid: uuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPeripheralConnectedChannel.setMessageHandler(nil)
    }
    /// (Android only) Check if any CompanionDeviceManager association exists.
    let hasCompanionDeviceAssociationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.hasCompanionDeviceAssociation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasCompanionDeviceAssociationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasCompanionDeviceAssociation()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasCompanionDeviceAssociationChannel.setMessageHandler(nil)
    }
    /// (Android only) Initiate CompanionDeviceManager association for a device.
    let requestCompanionDeviceAssociationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.requestCompanionDeviceAssociation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCompanionDeviceAssociationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceAddressArg = args[0] as! String
        api.requestCompanionDeviceAssociation(deviceAddress: deviceAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCompanionDeviceAssociationChannel.setMessageHandler(nil)
    }
    /// (Android only) Download a storage file natively, bypassing the per-packet
    /// platform-channel dispatch that throttles in background. Accumulates BLE
    /// notifications on the binder thread and writes directly to [outputPath].
    /// iOS throws 'unimplemented' — callers must check Platform.isAndroid.
    let downloadStorageFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.downloadStorageFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadStorageFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peripheralUuidArg = args[0] as! String
        let fileIndexArg = args[1] as! Int64
        let offsetArg = args[2] as! Int64
        let timerStartArg = args[3] as! Int64
        let outputPathArg = args[4] as! String
        api.downloadStorageFile(peripheralUuid: peripheralUuidArg, fileIndex: fileIndexArg, offset: offsetArg, timerStart: timerStartArg, outputPath: outputPathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadStorageFileChannel.setMessageHandler(nil)
    }
    /// (Android only) Acquire a CPU partial wake-lock so the OS does not throttle
    /// the processing isolate during VAD inference. Call before processAll; release
    /// in finally. iOS no-op.
    let acquireProcessingWakeLockChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.acquireProcessingWakeLock\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acquireProcessingWakeLockChannel.setMessageHandler { _, reply in
        do {
          try api.acquireProcessingWakeLock()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      acquireProcessingWakeLockChannel.setMessageHandler(nil)
    }
    /// (Android only) Release the CPU partial wake-lock acquired by
    /// [acquireProcessingWakeLock]. iOS no-op.
    let releaseProcessingWakeLockChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.releaseProcessingWakeLock\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseProcessingWakeLockChannel.setMessageHandler { _, reply in
        do {
          try api.releaseProcessingWakeLock()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseProcessingWakeLockChannel.setMessageHandler(nil)
    }
    /// (Android only) Push the next-sync epoch-ms to OmiBleForegroundService so it
    /// can display a native Chronometer countdown without Dart involvement.
    /// Pass 0 to clear (e.g. Manual Only mode). iOS no-op.
    let setNextSyncTimeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.setNextSyncTime\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNextSyncTimeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timestampMsArg = args[0] as! Int64
        do {
          try api.setNextSyncTime(timestampMs: timestampMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNextSyncTimeChannel.setMessageHandler(nil)
    }
    /// (Android only) Push the device battery level and the epoch-ms when it was
    /// read to OmiBleForegroundService so ID 2001 shows "78% · 3:45 PM".
    /// Call whenever a battery reading is obtained. iOS no-op.
    let setDeviceBatteryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.setDeviceBattery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDeviceBatteryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! Int64
        let timestampMsArg = args[1] as! Int64
        do {
          try api.setDeviceBattery(level: levelArg, timestampMs: timestampMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDeviceBatteryChannel.setMessageHandler(nil)
    }
    /// (Android only) Set the single foreground-service notification's title and
    /// text directly. Used by the Dart sync state machine to drive the one
    /// persistent notification (idle / connecting / syncing / processing / …).
    /// While a status is set, native suppresses its own connection-state text so
    /// the two don't fight. iOS no-op.
    let setSyncStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.setSyncStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSyncStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let textArg = args[1] as! String
        do {
          try api.setSyncStatus(title: titleArg, text: textArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSyncStatusChannel.setMessageHandler(nil)
    }
    /// (Android only) Keep the foreground service alive with no device connected
    /// so the idle "Next sync / Last Sync" notification persists across BLE
    /// disconnect and app background. true while auto-sync is on and a device is
    /// bound; false in Manual Only / unbound (reverts to connection-only service
    /// lifetime). iOS no-op.
    let setPersistentNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.setPersistentNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPersistentNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setPersistentNotification(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPersistentNotificationChannel.setMessageHandler(nil)
    }
    /// (Android only) Clear any Dart-pushed status text and let native resume
    /// owning the notification (connection state / idle). iOS no-op.
    let clearSyncStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_pigeon.BleHostApi.clearSyncStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSyncStatusChannel.setMessageHandler { _, reply in
        do {
          try api.clearSyncStatus()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSyncStatusChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BleFlutterApiProtocol {
  func onBluetoothStateChanged(state stateArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPeripheralDiscovered(peripheral peripheralArg: BlePeripheral, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDeviceReady(peripheralUuid peripheralUuidArg: String, services servicesArg: [BleService], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPeripheralDisconnected(peripheralUuid peripheralUuidArg: String, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCharacteristicValueUpdated(peripheralUuid peripheralUuidArg: String, serviceUuid serviceUuidArg: String, characteristicUuid characteristicUuidArg: String, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStateRestored(peripheralUuids peripheralUuidsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called by native (iOS BGProcessingTask / Android WorkManager) when a
  /// background sync should be triggered. Equivalent to a timer-fired sync tick
  /// but sourced from the OS scheduler instead of the Dart timer.
  func onBackgroundSyncRequested(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BleFlutterApi: BleFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonCommunicatorPigeonCodec {
    return PigeonCommunicatorPigeonCodec.shared
  }
  func onBluetoothStateChanged(state stateArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onBluetoothStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPeripheralDiscovered(peripheral peripheralArg: BlePeripheral, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onPeripheralDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDeviceReady(peripheralUuid peripheralUuidArg: String, services servicesArg: [BleService], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onDeviceReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralUuidArg, servicesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPeripheralDisconnected(peripheralUuid peripheralUuidArg: String, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onPeripheralDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralUuidArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCharacteristicValueUpdated(peripheralUuid peripheralUuidArg: String, serviceUuid serviceUuidArg: String, characteristicUuid characteristicUuidArg: String, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onCharacteristicValueUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralUuidArg, serviceUuidArg, characteristicUuidArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStateRestored(peripheralUuids peripheralUuidsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onStateRestored\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralUuidsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called by native (iOS BGProcessingTask / Android WorkManager) when a
  /// background sync should be triggered. Equivalent to a timer-fired sync tick
  /// but sourced from the OS scheduler instead of the Dart timer.
  func onBackgroundSyncRequested(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_pigeon.BleFlutterApi.onBackgroundSyncRequested\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
